fix: discussion tab
UMAprotocol/voter-dapp-v2 pull request #180
Opened 2023-02-02 13:13 UTC by ryanwolhuter

2023-02-02 13:14 UTC, ryanwolhuter commented on components/Panel/VotePanel/Discussion.tsx
> +      {loading ? (
this is all the same, just wrapped in a loading check

2023-02-02 13:15 UTC, ryanwolhuter commented on components/Panel/VotePanel/Discussion.tsx
> +  width: calc(var(--panel-width) - 15px);
absolute width to fix word wrap

2023-02-02 13:16 UTC, ryanwolhuter commented on components/Panel/VotePanel/Discussion.tsx
> +  word-break: break-word;
break word instead of break all on paragraph tags in the markdown, also to fix  word wrap

2023-02-02 13:16 UTC, ryanwolhuter commented on components/Panel/VotePanel/VotePanel.tsx
> +  content: VoteT;
I changed the name of this prop because it really just takes a vote and there's no need to have an alias type

2023-02-02 13:17 UTC, ryanwolhuter commented on components/Panel/VotePanel/VotePanel.tsx
> +  const { data: discussion, isFetching: discussionLoading } = useVoteDiscussion(
fetch this data here so that we can load it so long as soon as the user opens the panel

2023-02-02 13:18 UTC, ryanwolhuter commented on hooks/index.ts
> +export { useSign } from "./helpers/useSign";
my editor organized these in alphabetical order, I guess its nice so left it like that

2023-02-02 13:19 UTC, ryanwolhuter commented on hooks/queries/votes/useVoteDiscussion.ts
> +import { useQuery } from "@tanstack/react-query";
Renamed to avoid confusion between discussion and the thread associated with it

2023-02-02 13:19 UTC, ryanwolhuter commented on pages/api/discord-thread.ts
> +  VoteDiscussionT,
renamed type as above

2023-02-02 13:19 UTC, ryanwolhuter commented on types/ui.ts
> -export type VotePanelContentT = VoteT;
when I initially added these types there were going to be more kinds of panel content. since there is only one now, these are redundant

2023-02-02 13:20 UTC, ryanwolhuter commented on types/voting.ts
> -export const DiscordThreadsT = ss.array(DiscordThreadT);
removed these types because they are unused

2023-02-02 13:22 UTC, ryanwolhuter commented on components/Panel/VotePanel/VotePanel.tsx
> -      {hasResults ? (
this is the source of the bug where the discussion tab didn't show on active votes. active votes don't have results, so we'd never show the tabs

2023-02-02 16:17 UTC, daywiss approved these changes

2023-02-02 16:21 UTC, daywiss requested changes
was having an issue with panel being empty
1. reload page
2. open more details in past request
3. see panel empty

2023-02-03 07:32 UTC, ryanwolhuter commented
> was having an issue with panel being empty
> 
> 1. reload page
> 2. open more details in past request
> 3. see panel empty

oof thanks for catching this, it doesn't happen on local. I think I know the cause though, will fix now

2023-02-03 08:10 UTC, ryanwolhuter commented
> was having an issue with panel being empty
> 
> 1. reload page
> 2. open more details in past request
> 3. see panel empty

@daywiss I think this takes the prize for the dumbest mistake of the year so far.

The tabs component takes a `defaultValue` which is the string title of a chosen tab. In the logic I did `hasResults ? "Results" : "Discussion"`. However, the title of the tab is "Result", not "Results" 🥲 

I have no idea why this worked on my local but not in production. I think it has something to do with the load order and the fact that the result tab is already the first tab in the list.

Anyway it is fixed now 👍

2023-02-03 12:58 UTC, chrismaree commented
I tested this out and it looks like it works great to me! thanks for adding this so quickly

2023-02-03 13:06 UTC, chrismaree commented
one strange thing is some of the messages have a link that is broken, like this:
<img width="523" alt="2023-02-03 at 14 00 37@2x" src="https://user-images.githubusercontent.com/12886084/216609741-81cc6d5e-47c1-44c9-ba4f-2dbee1fea6a5.png">

if you click the link it takes you here https://media.discordapp.net/attachments/1058539248040542278/1058604844484669440/validation.log and is a dead link. 

when checking what the message actually has in discord it is a long "message log" https://discord.com/channels/718590743446290492/1059516345127030815/1059536132213317652 that looks like this in discord 
<img width="414" alt="2023-02-03 at 14 02 25@2x" src="https://user-images.githubusercontent.com/12886084/216610065-7655f950-c559-41eb-9ed2-07ac5eaa98a7.png">

I looked into what the link that is produced from the discord serverless output and compared it to the one that is produced by the discord app itself:
- link produced in our dapp(dead link):  https://media.discordapp.net/attachments/1058539248040542278/1058604844484669440/validation.log
- link produced by discord (works to download the file): https://cdn.discordapp.com/attachments/1059516345127030815/1059536131856797746/validation.log

I played with this and basically what we need to do is update the discord serverless function such that if _any message contains a `media.discordapp.net`_ string we replace it with `cdn.discordapp.com`_. This will keep the formatting exactly the same as it is now but will actually let us pull down the log files if someone clicks the link. I think we should add this to this PR as well so we can test it all together. @ryanwolhuter can you do that?

2023-02-03 13:57 UTC, daywiss approved these changes
nice work

2023-02-06 07:25 UTC, merged